spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:hotels_db
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8000